export const dashElement = '<span class="dashes">-</span>';

export const alphabetLetters = "abcdefghijklmnopqrstuvwxyz";

export const categories = {
    anime: [
        "naruto",
        "bleach",
        "onepiece",
        "dragonball",
        "kaijuno8",
        "jujutsukaisen",
        "onepunchman",
        "steinsgate",
        "mobpsycho",
        "deathnote",
        "codegeass",
        "drstone",
        "sololeveling",
        "chainsawman",
        "vinlandsaga",
    ],
    food: [
        "pizza",
        "sushi",
        "tacos",
        "dogbugi",
        "tsuivan",
        "burger",
        "pasta",
        "ramen",
        "chicken",
        "donut",
        "cake",
        "cookie",
        "sashimi",
        "steak",
        "sandwich",
        "burrito",
        "popcorn",
        "soup",
        "curry",
        "bulgogi",
    ],
    countries: [
        "france",
        "mexico",
        "brazil",
        "canada",
        "sweden",
        "japan",
        "germany",
        "italy",
        "spain",
        "australia",
        "kazakhstan",
        "luxembourg",
        "azerbaijan",
        "croatia",
        "denmark",
        "liechtenstein",
        "mozambique",
        "madagascar",
        "uzbekistan",
        "mauritania",
    ],
};
